---
kind: pipeline
name: apps/player

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'apps/player/**/*.{js,vue}'

- name: integration
  image: cypress/base:10
  commands:
    - npx cypress install
    - npx lerna run integration:build --scope @podlove/player
    - npx lerna run integration:server --scope @podlove/player
    - npx lerna run integration:ci --scope @podlove/player

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/player

---
kind: pipeline
name: apps/web-player

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'apps/web-player/**/*.{js,vue}'

- name: integration
  image: cypress/base:10
  commands:
    - npx cypress install
    - npx lerna run integration:build --scope @podlove/web-player
    - npx lerna run integration:server --scope @podlove/web-player
    - npx lerna run integration:ci --scope @podlove/web-player

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/web-player

---
kind: pipeline
name: packages/components

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/components/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest packages/components

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/components

---
kind: pipeline
name: packages/player-actions

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/player/actions/**/*.{js,vue}'

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/player-actions

---
kind: pipeline
name: packages/player-sagas

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/player/sagas/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest 'packages/player/sagas'

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/player-sagas

---
kind: pipeline
name: packages/player-state

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/player/state/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest 'packages/player/state'

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/player-state

---
kind: pipeline
name: packages/utils

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: lint
  image: node:10
  commands:
    - npx eslint 'packages/utils/**/*.{js,vue}'

- name: test
  image: node:10
  commands:
    - npx jest 'packages/utils'

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/utils

---
kind: pipeline
name: docs/web-player

steps:
- name: bootstrap
  image: node:10
  commands:
    - npm set unsafe-perm true
    - npm i
    - npx lerna bootstrap --hoist

- name: build
  image: node:10
  commands:
    - npx lerna run build --scope @podlove/docs-web-player
