version: '3'

networks:
  podlove-ui-net:
    external: true

volumes:
  podlove-ui-npm-cache:
    external: true

services:
  node:
    image: node:10-alpine
    volumes:
      - ../:/ui:cached
      - podlove-ui-npm-cache:/home/node/.npm
    ports:
      - '${PODLOVE_UI_STORYBOOK_DEV_PORT:-6006}:${PODLOVE_UI_STORYBOOK_DEV_PORT:-6006}'
    user: 'node'
    working_dir: /ui
    environment:
      NODE_ENV: development
      IS_IN_DOCKER: 1
      DOMAIN: node.${PODLOVE_UI_DOMAIN:-podlove-ui.test}
      STORYBOOK_DEV_DOMAIN: storybook-dev.${PODLOVE_UI_DOMAIN:-podlove-ui.test}
      STORYBOOK_DEV_PORT: ${PODLOVE_UI_STORYBOOK_DEV_PORT:-6006}
    command: 'node'
    labels:
      - 'traefik.storybook-dev.frontend.rule=Host:storybook-dev.${PODLOVE_UI_DOMAIN:-podlove-ui.test}'
      - 'traefik.storybook-dev.port=${PODLOVE_UI_STORYBOOK_DEV_PORT:-6006}'
      - 'traefik.enable=true'
    networks:
      podlove-ui-net:
        aliases:
          - storybook-dev.${PODLOVE_UI_DOMAIN:-podlove-ui.test}
